name: fl_mirror
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/Mbouziani/fl_mirror
repository: https://github.com/Mbouziani/fl_mirror
issue_tracker: https://github.com/Mbouziani/fl_mirror/issues
documentation: https://github.com/Mbouziani/fl_mirror#readme

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

# Optional but useful
topics:
  - cqrs
  - validation
  - bus
  - flutter
  - dart